@startuml
scale max 1920 width
scale max 1080 height

'left to right direction

skinparam state {
    SeparatorThickness 0
    FontSize 22
    ArrowFontSize 16
    LegendFontSize 24
}

'state Manual
'state Horizontal_Sweep
'state Vertical_Sweep
'state Horizontal_Max
'state Vertical_Max


[Manual] --> [Horizontal Sweep] : BTN_C
[Horizontal Sweep] --> [Horizontal Sweep] : CNT_L / SERVO_L

[Horizontal Sweep] --> [Horizontal_Max] : CNT_L
[Horizontal Max] --> [Horizontal Max] : CNT_R / SERVO_R

[Horizontal Max] -->[ Vertical Sweep] : CNT_RU
[Vertical Sweep] -->[ Vertical Sweep] : CNT_D / SERVO_D

[Vertical Sweep] --> [Vertical Max] : CNT_D
[Vertical Max] --> [Vertical Max] : CNT_RU / SERVO_U

[Vertical Max] --> [Manual] : CNT_RU

@enduml

